version: '3.3'

services:
  fastapi_service:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
    depends_on:
      - redis
    ports:
      - "0.0.0.0:8888:8000"
#      - "127.0.0.1:8888:8000"
#    env_file:
#      - .env
    volumes:
      - ./:/home/app
#    networks:
#      - my_net
#  db_postgres:
#    image: postgres:14.3-alpine
#    hostname: db_postgres
#    container_name: db_postgres
#    restart: on-failure
    environment:
      - SMARTHOME_BAK_LOG_LEVEL=DEBUG
      - SMARTHOME_BAK_PG_DSN=sqlite:////code/prod.db
      - SMARTHOME_BAK_REDIS_HOST=redis
      - SMARTHOME_BAK_REDIS_PORT=6379
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5434:5432"
#    volumes:
#      - db-postgres:/var/lib/postgresql/data
    networks:
      - my_net
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    expose:
      - 6381
#    volumes:
#      - /path/to/local/dаta:/root/redis
#      - /compose/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
#      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - my_net

  redis-debug:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    expose:
      - 6380
#    volumes:
#      - /path/to/local/dаta:/root/redis
#      - /compose/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
#      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
#    networks:
#      - my_net

networks:
  my_net:
    driver: bridge
#    external: true

