version: '3.3'

services:
  fastapi_service:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: fastapi_service
    container_name: fastapi_service
#    depends_on:
#      - db_postgres
    ports:
      - "8000:8000"
#    env_file:
#      - .env
    volumes:
      - ./:/home/app
#    networks:
#      - my-net
#  db_postgres:
#    image: postgres:14.3-alpine
#    hostname: db_postgres
#    container_name: db_postgres
#    restart: on-failure
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5434:5432"
#    volumes:
#      - db-postgres:/var/lib/postgresql/data
#    networks:
#      - my-net
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379
#    volumes:
#      - /path/to/local/d–∞ta:/root/redis
#      - /compose/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
#      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
#    networks:
#      - my-net

networks:
  my-net:
    external: true